# Generated by Django 5.1.1 on 2024-10-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_adress_author_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='adress',
            new_name='address',
        ),
    ]
